name: Run lint for all the files in src folder
'on': push
jobs:
  lint-runner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run ESLint
        run: |
          npm install
          npm run lint
        continue-on-error: false
      # - name: Run ESLint
      #   run: node_modules/.bin/eslint --ext js src
