name: Run lint for all the files in src folder
'on': push
jobs:
  lint-runner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - run: |
          npm run lint
